---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`localhost`) && Path(`/`)
      kind: Rule
      services:
        - name: whoami
          port: 80
    - match: Host(`whoami.127.0.0.1.nip.io`) && Path(`/`)
      kind: Rule
      services:
        - name: whoami
          port: 80
  tls:
    secretName: cert-whoami
    domains:
      - main: whoami.127.0.0.1.nip.io
